### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by SebGruber1996** [compstat-lmu/rlR#13]
Hi!
I had a few issues while installing rlR and running its basic example.

- export(AgentFactory) needs to be changed to export(makeAgent) in the NAMESPACE file (I already wrote this to Xudong in an email, but since then two more other issues occured, and for completeness sake I mention it again here)
- the newest tensorflow version was installed, but my CPU wasn't compatible with it. I needed to manually reinstall tensorflow v1.5 to make keras work. Even though this is a rare edge case (keyword: AVX compatibility of CPU) a mention or clue somewhere would be nice - I needed quite long to figure this one out.
- similar issue with the gym package: It seems that env.render(close=True) is used in rlR, but this is only supported in gym v0.9.5, while leading to a crash in all newer versions. I also got the newest version by default and had to reinstall older versions 5 times (v0.10.3, v0.10.2, v0.10.0, v0.9.6 and finally v0.9.5) until I got to a version that still support the "close=True" argument. I can see two appropriate options: - maybe a fix in the code (newer versions of gym use "env.close()") - or maybe specifying that gym v0.9.5 is required

Besides these minor issues the first example did run quite nicely.

Greetings,
Sebastian

**Comment by smilesun** [comment]
- export: fixed
- tensorflow: I think you need to change some flag in the compilation, you do not need the best cpu to run tensorflow I guess. 
- doing

**Comment by smilesun** [comment]
https://github.com/openai/gym/releases

From above, actually the new versions are upgraded only these 3 months.

**Comment by smilesun** [comment]
fixed, Latest commit 7bc4b8d
I have used the latest gym version
